version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dsapp
    environment:
      DB_HOST: db
      CONFIG_PATH: "/local.yaml"
    ports:
     - "8080:8080"
    depends_on:
      - "db"
  db:
    image: "postgres:latest"
    container_name: dsdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
     - "5432:5432"
